### ISSUE TITLE
Feature Request!

### ISSUE THREAD

**Issue by a092devs** [AyraHikari/Nana-TgBot#3]
Add support for: 
1. Google Search: searches google about the query
2. Reverse Image Search: does a reverse search of any image from google
3. Add Lydia: An AI bot by Intellivoid
4. Lyrics finder

**Comment by najahiiii** [comment]
"Featue request" is an issue now, okay.

**Comment by alanndz** [comment]
@a092devs @AyraHikari Lydia apaan pak?? 🤔

**Comment by a092devs** [comment]
> "Featue request" is an issue now, okay.

where do I post it then?  it is easy for the developer to keep track.

**Comment by ProtoChuz** [comment]
@a092devs

**Comment by Muhajaya** [comment]
> > "Featue request" is an issue now, okay.
> 
> where do I post it then? it is easy for the developer to keep track.

Ayra's Bot Support
Group: https://t.me/AyraSupport
https://t.me/AyraSupport

**Comment by a092devs** [comment]
> > > "Featue request" is an issue now, okay.
> > 
> > 
> > where do I post it then? it is easy for the developer to keep track.
> 
> Ayra's Bot Support
> Group: https://t.me/AyraSupport
> https://t.me/AyraSupport

Feature request on Telegram Group is not a good idea! Its always preferred to use github issues section to add feature request, bugs etc

**Comment by AyraHikari** [comment]
It's okay, i've labeled enchancement now

**Comment by AyraHikari** [comment]
- [x] Google Search: searches google about the query
- [x] Reverse Image Search: does a reverse sesrch of any image from google
- [ ] Add Lydia: An AI bot by Intellivoid
- [ ] Lyrics finder

Commits was pushed into dev branch.
For reverse image search (google), yeah it can, but just give you to a link, not a from X (sorry, i don't want to make it public for my AI reverse engine 😅)
For Lydia and lyric finder, i dont think it free, if you found a free api, please add comment here

**Comment by ProtoChuz** [comment]
ai :/

-------- Pesan asli --------
Di 25 Okt 2019 07.54, Ayra Hikari menulis:

**Comment by AyraHikari** [comment]
Yes, AI reverse image, it can search source, HD image, otherlike image, etc.
Can't show code because maybe someone will make it for commercial

**Comment by a092devs** [comment]
> * [x]  Google Search: searches google about the query
> * [x]  Reverse Image Search: does a reverse sesrch of any image from google
> * [ ]  Add Lydia: An AI bot by Intellivoid
> * [ ]  Lyrics finder
> 
> Commits was pushed into dev branch.
> For reverse image search (google), yeah it can, but just give you to a link, not a from X (sorry, i don't want to make it public for my AI reverse engine )
> For Lydia and lyric finder, i dont think it free, if you found a free api, please add comment here

Lydia is free we can make an account frome here https://coffeehouse.intellivoid.info/login and request for api in https://t.me/intellivoid telegram group.
For Lyrics, this provides free API: genius.com/api-clients
